### ISSUE TITLE
DataTables warning: table id=programs - org.springframework.data.mapping.PropertyReferenceException: No property media found for type Programs!

### ISSUE THREAD

**Issue by chano21** [darrachequesne/spring-data-jpa-datatables#102]
Error : 
DataTables warning: table id=programs - org.springframework.data.mapping.PropertyReferenceException: No property media found for type Programs!

When i click to sorting colum, I had this issue. 

html : 
```
         <th>id</th>
	<th>media_name</th> < - I cllicked this one to sort
	<th>media_code</th>  < - I cllicked this one to sort
	<th>pgCode       </th>
	<th>pgName       </th>
	<th>pgSubName    </th>

```
Only CamelCase colum have this issue. how can i solve???

**Comment by darrachequesne** [comment]
How do you init your table? Maybe some typo between `media_name` and `media.name` (since the error mentions `No property media found`) ?

Else, could you please provide a way to reproduce?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
