### ISSUE TITLE
How to use ColumnParameter

### ISSUE THREAD

**Issue by hendisantika** [darrachequesne/spring-data-jpa-datatables#115]
I created repo follow your implementation.
But, I have an issue.
How to use ColumnParameter?

https://github.com/hendisantika/SpringBoot-DataTable

Thanks

**Comment by darrachequesne** [comment]
Hi! Could you please explain what you are trying to do?

**Comment by hendisantika** [comment]
I will explain it to you my issue tomorrow ya.
I have to go meeting right now.
But, thank for your response.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
