### ISSUE TITLE
How can I use Pagination?

### ISSUE THREAD

**Issue by sebasira** [darrachequesne/spring-data-jpa-datatables#117]
I've been using this for a long time and really love it. I'd like to reduce the rendering/request time when loading a big list of data.

I've notice that from the server side I'm returning EVERY registry from DB and pass it to the DataTable.

I've never use Pagination / Pageable and I'd like to. Can you guide me on how to achive it using this library? I don't know if I should do it in the server or is there a way to instruct `spring-data-jpa-datatables` to page the results.

Thanks!

**Comment by darrachequesne** [comment]
@sebasira hi! the number of results returned by the server is based on the `length` property in the input [here](https://github.com/darrachequesne/spring-data-jpa-datatables/blob/61ba124db6bd6c5370cd0861dff330d9a40de726/src/main/java/org/springframework/data/jpa/datatables/mapping/DataTablesInput.java#L34-L42).

I think, in your case, the length must be `-1`, so every record is fetched, is that the case?

**Comment by sebasira** [comment]
@darrachequesne thanks for your reply! I've check this because I didn't know what that `length` was. And after debugging I found it very useful along with the `start` property. I didn't know about them and I think they would be what I need to use achieve the pagination.

The problem on my program is that I'm **always** returning the full list of entities, according to this code:

```
dataTablesOutput = dataTableRepository.findAll(input);
```

As you can see I'm not taking into account the properties I've mentioned before because I did not know about them.

I've never use pagination, so I don't know how to implement it in my side. Can you guide me on how can I change my code to make use of those properties? Thank you and please excuse my lack of knowledge.

**Comment by sebasira** [comment]
I try to change the **findAll** method use another one, but the only options I had where findAll and findOne.

This is the code of my Repository:

```
@Repository
public interface UsuarioDataTableRepository extends DataTablesRepository<Usuario, String> {
}
```

**Comment by sebasira** [comment]
Please **DISMISS** this issue... It's already working paginated I just did not realize that. After exploring and understanding `size` and `start`, I started debugging a see that the size of the `data` attribute is the specified length.

I was confused by `recordsTotal` and `recordsFiltered` which shows the whole size of the Table
