### ISSUE TITLE
Failed to Compile JSP Upon Importing The Library

### ISSUE THREAD

**Issue by hishamabri** [darrachequesne/spring-data-jpa-datatables#121]
Hi contributors
First of all thanks for the library.

I am facing an issue where as soon as I import the library on maven. My JSP files fail to compile immediatlely.
Not sure if there's a dependency conflict. The error is also somewhat suspicious. Its complaining about JDK 1.5 and not being able to parametize things like a HashSet<>

1 - org.apache.jasper.JasperException: Unable to compile class for JSP: 
An error occurred at line: [23] in the generated java file: [path/to/jsp/WEB-INF/views/jsp.java]
Syntax error, parameterized types are only available if source level is 1.5 or greater
2 - An error occurred at line: [36] in the generated java file: [path/to/jsp/WEB-INF/views/jsp.java]
'<>' operator is not allowed for source level below 1.7
3 - An error occurred at line: [36] in the generated java file: [path/to/jsp/WEB-INF/views/jsp.java]
Incorrect number of arguments for type HashSet<E>; it cannot be parameterized with arguments <>

Any ideas will be greatly appreciated.

**Comment by darrachequesne** [comment]
I'm not sure this is related to the library. Could you please provide a way to reproduce (maybe a sample repository)?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
