### ISSUE TITLE
JPARepository not working after creating DatatableRepository

### ISSUE THREAD

**Issue by kapil-signity** [darrachequesne/spring-data-jpa-datatables#122]
Cannot Autowire normal JPA Repository of entity if we create DatatableRepository of same entity.? Why?
Then how how we create JPARepository of the same entity along with DatatableRepository?

**Comment by darrachequesne** [comment]
Hi!

The `DataTablesRepositoryImpl` class extends the [SimpleJpaRepository](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/support/SimpleJpaRepository.html) class (which itself implements the [JpaRepository](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html) interface):

https://github.com/darrachequesne/spring-data-jpa-datatables/blob/ea534b9325140b5739366f4d1d155ac2746030c7/src/main/java/org/springframework/data/jpa/datatables/repository/DataTablesRepositoryImpl.java#L16-L17

So you should have access to all the methods. Or am I missing something?
