### ISSUE TITLE
Only get 10 rows of data

### ISSUE THREAD

**Issue by fauzansaef** [darrachequesne/spring-data-jpa-datatables#126]
Hello @darrachequesne  , I have a problem when i want to findAll() my entity .
Why if i'm using DataTablesRepository only get 10 rows of data from my table on database? But if i'm using JpaRepository it can get all the datas.  Please help me.

**Comment by darrachequesne** [comment]
Hi! You can retrieve all entities with:

```java
DataTablesInput input = new DataTablesInput();
input.setLength(-1);
repository.findAll(input);
```

**Comment by fauzansaef** [comment]
i got the problem , thanks bro @darrachequesne
