### ISSUE TITLE
Disable lower() on search specification

### ISSUE THREAD

**Issue by dawnpeace** [darrachequesne/spring-data-jpa-datatables#127]
Hello I'm using sql server on my project and I needed to search on text datatype which I couldn't perform because it would throw error "datatype text is invalid for argument 1 of lower" on sql
is there anyway to disable the lower function ?
Thanks

**Comment by darrachequesne** [comment]
Hi! This is not currently possible, but we could indeed add an option for this.

That being said, according to the documentation:

> character_expression must be of a data type that is implicitly convertible to varchar

I wonder why it does not work with the `text` datatype.

Reference:
- https://docs.microsoft.com/en-us/sql/t-sql/functions/lower-transact-sql?view=sql-server-ver15
- https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver15

**Comment by dawnpeace** [comment]
Thanks for the reply 
Unfortunately It is not possible to lower `text` data type for SQL Server
It would throw `Argument data type text is invalid for argument 1 of lower function.` error.
The input needed to be casted to `varchar` datatype in order to make lower function works

I will close this then
