### ISSUE TITLE
How to Work with UserDTO

### ISSUE THREAD

**Issue by Vaibhav-Andhale** [darrachequesne/spring-data-jpa-datatables#140]
i'm going through your document and i found below code but what is "toUserDTO".
Please explain.
@RestController
public class UserRestController {

  @Autowired
  private UserRepository userRepository;

  @RequestMapping(value = "/data/users", method = RequestMethod.GET)
  public DataTablesOutput<UserDTO> getUsers(@Valid DataTablesInput input) {
    return userRepository.findAll(input, **toUserDTO**);
  }
}

**Comment by darrachequesne** [comment]
The `toUserDTO()` method maps the User instance to a UserDTO instance, either with:

- manual mapping

```java
  public UserDTO toUserDTO(User user) {
    UserDTO dto = new UserDTO();
    dto.setId(user.getId());
    // ...
    return dto;
  }
```

- or by using a library like [MapStruct](https://mapstruct.org/) or [Orika](http://orika-mapper.github.io/orika-docs/)

**Comment by Vaibhav-Andhale** [comment]
Hi @darrachequesne ,
Thanks for response.
I did something like you.

public Function<User, UserDTO> createConverter(){
		return (Function<User, UserDTO>) (input) ->{
			UserDTO dto= new UserDTO();
			dto.setId(input.getId)			
			//...
			return dto;
		};
	}
