### ISSUE TITLE
Duplicates items after filtering

### ISSUE THREAD

**Issue by sebasira** [darrachequesne/spring-data-jpa-datatables#142]
I having and issue with an Entity that has a `@ManyToMany` association. It's a `Store` and a `StoreCategory` many stores can be associated to many categories.

I have an `Specification` to search (like) the associated categories. And after:

```java
dataTablesOutput = dataTableRepository.findAll(input, allColumnsSpecs);
```

I have this:
<img width="539" alt="Screen Shot 2022-01-08 at 11 49 42" src="https://user-images.githubusercontent.com/11217669/148650563-c5ebd55d-07b4-4f05-b9d3-cb657669b2b2.png">

As you can see i have 2 **recordsTotal** and 3 **recordsFiltered** so after filtering I have more records than the total. And as you can see, items 0 and 1 are the same Entity.

What I'm doing to solve this is remove duplicates like this:

```java
List<Integer> listWithDuplicates = Lists.newArrayList(5, 0, 3, 1, 2, 3, 0, 0);
List<Integer> listWithoutDuplicates = new ArrayList<>(
      new LinkedHashSet<>(listWithDuplicates));
```
Is this a bug or am I doing something wrong?

**Comment by darrachequesne** [comment]
Hi! Could you please provide a basic example reproducing the issue? You can fork the project here: https://github.com/darrachequesne/spring-data-jpa-datatables-sample/

A few things that I can think of:

- are you fetching the StoreCategory eagerly with `@ManyToMany(fetch = FetchType.EAGER)`?
- did you check the SQL logs with `spring.jpa.properties.hibernate.show_sql=true`?

Related: https://github.com/darrachequesne/spring-data-jpa-datatables/issues/87

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
