### ISSUE TITLE
Add support for Spring Boot 3.0.0

### ISSUE THREAD

**Issue by dellui** [darrachequesne/spring-data-jpa-datatables#145]
Hello.
I can use your spring-data-jpa-datatable with Spring Boot 2.7.4 and all wrok's fine!

With spring boot 3.0.0 I have compatibility issue (No property findAll found for type) 

Can you add support for Spring boot 3.0.0 or suggest me some workaround ?

Thanks.
Ciao.
Gigi

**Comment by darrachequesne** [comment]
Hi! I think we will have to wait for the GA release, the `spring-boot-dependencies` module is not updated on maven yet: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies

Reference: https://github.com/spring-projects/spring-shell/releases/tag/v3.0.0-M1

Do you know the effort needed to migrate to 3.0.0?

**Comment by dellui** [comment]
Hello darrachequesne.
Thank you for your answer.
I know, I know...it's certainly complex but...I tried to ask you anyway :)

Ciao.
Gigi

**Comment by darrachequesne** [comment]
Support for Spring Boot 3 was added in version [6.0.0](https://github.com/darrachequesne/spring-data-jpa-datatables/releases/tag/v6.0.0) :rocket:
