### ISSUE TITLE
Is it possible to do a regular expression search using ~ in PostgreSQL?

### ISSUE THREAD

**Issue by fooo19** [darrachequesne/spring-data-jpa-datatables#148]
I would like to achieve regular expression searches by using PostgreSQL.
In PostgreSQL, I can search with the following query.

`SELECT * FROM table WHERE id ~ '.*';`

I have looked into the possibility of achieving this with reference to ticket #31, but '~' is an operator, so criteriaBuilder.function() cannot be used.
https://github.com/darrachequesne/spring-data-jpa-datatables/issues/31

Is there any way to make this happen?

**Comment by darrachequesne** [comment]
Hi! I guess you already know it, but Postgresql 15 now has a `regexp_like()` method.

Reference: https://www.postgresql.org/docs/15/functions-matching.html

For previous versions, I'm not sure whether it's possible.
