### ISSUE TITLE
enable datatable repositories without using DatatablesJpaRepositoryBean

### ISSUE THREAD

**Issue by KrunchMuffin** [darrachequesne/spring-data-jpa-datatables#155]
One of our devs want to know "is it possible to enable datatable repositories without using DatatablesJpaRepositoryBean".

We also have envers and already have this set
`@EnableJpaRepositories(repositoryFactoryBeanClass = CustomEnversRevisionRepositoryFactoryBean.class)`

**Comment by darrachequesne** [comment]
I don't think this is possible.

However, you should be able to restrict the scope of the factory with the `basePackages` option:

```java
@Configuration
@EnableJpaRepositories(repositoryFactoryBeanClass = CustomEnversRevisionRepositoryFactoryBean.class, basePackages = "mypackage.envers")
public class EnversConfiguration {}

@Configuration
@EnableJpaRepositories(repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class, basePackages = "mypackage.datatables")
public class DataTablesConfiguration {}
```
