### ISSUE TITLE
There is the possibility of deactivating the recordsTotal?           

### ISSUE THREAD

**Issue by bonanidr** [darrachequesne/spring-data-jpa-datatables#164]
There is the possibility of deactivating the recordsTotal?

**Comment by bonanidr** [comment]
Thanks for the answer.
In my case, I have a table with many thousands of records, which has cost my database.

**Comment by darrachequesne** [comment]
This library only fetches the necessary entities, so it should not create much load on your database, even with millions of rows.

Each HTTP request creates 3 SQL queries:

- `select count(*) from <the table>` => `recordsTotal`
- `select count(*) from <the table> where <some filters>` => `recordsFiltered`
- `select col1, col2, ... from <the table> where <some filters> OFFSET x LIMIT y` => the list of records to be displayed

**Comment by bonanidr** [comment]
Even a well-modeled table with several request indexes with count(*) fullscan generates performance loss.
select count(*) from <the table> => recordsTotal
but I understand I will change my process to refine the filters.
thanks
