### ISSUE TITLE
error，factory-class cause exception

### ISSUE THREAD

**Issue by wangjia2016** [darrachequesne/spring-data-jpa-datatables#18]
**when use

factory-class="org.springframework.data.jpa.datatables.repository.DataTablesRepositoryFactoryBean"

it cause error as follows:**

`Servlet.service() for servlet [jsp] in context with path [/mgr] threw exception [java.lang.LinkageError: loader constraint violation: when resolving interface method "javax.servlet.jsp.JspApplicationContext.getExpressionFactory()Ljavax/el/ExpressionFactory;" the class loader (instance of org/apache/jasper/servlet/JasperLoader) of the current class, org/apache/jsp/index_jsp, and the class loader (instance of org/codehaus/plexus/classworlds/realm/ClassRealm) for resolved class, javax/servlet/jsp/JspApplicationContext, have different Class objects for the type avax/el/ExpressionFactory; used in the signature] with root cause
java.lang.LinkageError: loader constraint violation: when resolving interface method "javax.servlet.jsp.JspApplicationContext.getExpressionFactory()Ljavax/el/ExpressionFactory;" the class loader (instance of org/apache/jasper/servlet/JasperLoader) of the current class, org/apache/jsp/index_jsp, and the class loader (instance of org/codehaus/plexus/classworlds/realm/ClassRealm) for resolved class, javax/servlet/jsp/JspApplicationContext, have different Class objects for the type avax/el/ExpressionFactory; used in the signature
	`

when remove factory-class="org.springframework.data.jpa.datatables.repository.DataTablesRepositoryFactoryBean"

it works!

**Comment by darrachequesne** [comment]
Hi! According to the stacktrace, it seems that there may be a version conflict about the `javax.el` dependency, but I can't tell much more, could you provide some further context please?

A simple project reproducing the issue would be awesome :angel:

**Comment by wangjia2016** [comment]
![qq 20160614092229](https://cloud.githubusercontent.com/assets/16084076/16028405/95f64620-3211-11e6-8621-2cda37fe3255.png)

 Maven dependency:


<dependency>
			<groupId>com.github.darrachequesne</groupId>
			<artifactId>spring-data-jpa-datatables</artifactId>
			<version>2.3</version>
	
			<exclusions>
				<exclusion>
					<artifactId>javax.el-api</artifactId>
					<groupId>javax.el</groupId>
				</exclusion>
			</exclusions>
		</dependency>


it works! THKS

**Comment by darrachequesne** [comment]
Great news! :+1:
