### ISSUE TITLE
Java 8 date objects not rendering

### ISSUE THREAD

**Issue by Rejinderi** [darrachequesne/spring-data-jpa-datatables#19]
![image](https://cloud.githubusercontent.com/assets/4333016/16002349/c2a3e2dc-3189-11e6-9d0f-8813db739b28.png)

Local datetime objects are rendered as [Object object] any ways to have them rendered properly?

**Comment by darrachequesne** [comment]
Hi! I guess you have found the solution by yourself, may I ask if you could share it, for future reference?

For my part, I would have suggested using [Moment.js](http://momentjs.com/) to format that field.

**Comment by dawnofclarity** [comment]
FWIW, I used moment.js as follows:

```javascript
function renderDate(data, type, row) {
  if (data) {
    var dm = moment({y: data.year, M: data.monthValue - 1, d: data.dayOfMonth});
    switch (type) {
      case 'display':
        return dm.format("D MMM YY");
      default:
        return dm.format("X");
    }
  }
  else {
    return '';
  }
}
```

Then apply to your column using the ```render``` keyword

```javascript
      {
        'data': "txnDate",
        'render': renderDate
      },
```

The same technique can be applied to LocalTime and LocalDateTime too.

**Comment by darrachequesne** [comment]
@dawnofclarity great, thanks! :+1:
