### ISSUE TITLE
Making spring-data-datatables work with MongoDB

### ISSUE THREAD

**Issue by prateekmathur1991** [darrachequesne/spring-data-jpa-datatables#25]
I have a web page that is configured with DataTables client side configuration, and needs to be converted to DataTables server side configuration. The DB we are using is MongoDB.

Any ideas as to how can I make this library work with MongoDB?

**Comment by darrachequesne** [comment]
Hi! MongoDB is currently not supported. The mappings (`DataTablesInput` and all) are the same, but the querying part has to be implemented through the Mongodb Criteria API:

`Query query = new Query(Criteria.where("firstName").is("Harry"));`

It should maybe have its own module, something like `spring-data-mongodb-datatables`.

**Comment by darrachequesne** [comment]
Edit: there is already an implementation there https://github.com/biggates/spring-data-mongodb-datatables (but it does not seem to be deployed on Maven central sadly)

**Comment by paulo-maia** [comment]
Any idea on how to configure the mongo repository to use with this module? I'm always getting new exceptions, can't get it to work... Do I need a specific Config class? I'm a beginner in Springboot and in my examples a simply configure mongo using the application.properties file. 
If at all possible, if someone provided a working example with MongoDB I would be eternally grateful...

**Comment by darrachequesne** [comment]
@paulo-maia I am not the author of the spring-data-mongodb-datatables module (never used it, in fact), did you check the example over there?

**Comment by paulo-maia** [comment]
I did, couldn't get it to work thought... I know that this module is not yours, just thought someone in this thread could post an example, the other one seems to be a bit abandoned.

**Comment by paulo-maia** [comment]
Got it working, no global search though!
