### ISSUE TITLE
Add jackson-datatype-jsr310

### ISSUE THREAD

**Issue by brunoguadagnini** [darrachequesne/spring-data-jpa-datatables#27]
What do you think about adding the jackson-datatype-jsr310 of reference to support the new date and time library of java 8?

https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310

Thank you!

**Comment by darrachequesne** [comment]
@brunoguadagnini sorry for the delay! May I ask what the use case is, exactly? Shouldn't that package be included on a per-project basis?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
