### ISSUE TITLE
How do I use VO replace Entity with DataTablesRepository

### ISSUE THREAD

**Issue by lidaling** [darrachequesne/spring-data-jpa-datatables#30]
Hi,
I want to return VOs to client ,how to repalce Entity with VO with DataTablesRepository.
Thanks

**Comment by darrachequesne** [comment]
Please see the converter argument here: `DataTablesRepository#findAll(DataTablesInput input, Converter<T, R> converter);`

**Comment by lidaling** [comment]
It works
