### ISSUE TITLE
Can I query two tables with SQL?

### ISSUE THREAD

**Issue by Acris** [darrachequesne/spring-data-jpa-datatables#34]
Hello,
I wanna query datas from two tables not all datas with SQL and display result on datatables ,such as "select a.title,b.name from table_a as a, table_b as b where a.id=b.aid". These two tables don't have one to one or many to one relationship. I googled it but I didn't find an answer. Can you tell me is it possible to implement with spring-data-jpa-datatables? Thank you very much.

**Comment by darrachequesne** [comment]
Hi @Acris, I'm afraid that case is not covered, as the library relies on JPA mappings / relationships.

From your question, it's not clear, do you already have entities mapping your tables?

Some workaround I could think of:
- create two other `@Entity` which will map your tables with a `@OneToOne` relationship for that use-case only
- if your filters only applies to `table_a`, use the library to fetch the entities from `table_a`, and then in a second time fetch related entities from `table_b`

**Comment by Acris** [comment]
Thanks for your reply.
As you say,it is nesisery to add relationships in entity class, right?

**Comment by Acris** [comment]
I want to use custom query with @Query annotation, but I don't know how to deal with DatatablesInput parameter.

**Comment by darrachequesne** [comment]
To use `DataTablesRepository#findAll()` method, the relationships are indeed needed.

The `DataTablesInput` just maps the payload sent by the client-side (described [here](https://datatables.net/manual/server-side)), you should be able to use it to use it with your custom  `@Query`.

Please see:
* `DatatablesInput#getColumn(String columnName)`
* `ColumnParameter.getSearch().getValue();`

**Comment by Acris** [comment]
@darrachequesne I got it, thank you very mush 👍
