### ISSUE TITLE
QueryDSL Support

### ISSUE THREAD

**Issue by efriandika** [darrachequesne/spring-data-jpa-datatables#4]
Please add support to query DSL :dancer:

**Comment by darrachequesne** [comment]
Hi! Thanks for your interest. Would a method like that suit your needs?
```
DataTablesOutput<T> findAll(DataTablesInput input, com.mysema.query.types.Predicate predicate);
```

**Comment by efriandika** [comment]
Yes.. that's right.. :D 
Thanks @darrachequesne

**Comment by olc-olivier** [comment]
Hi,

Do you think it is possible to map nested object, deeper ?

Ex:  
class A
   B b

class B
   Set<Translations> translations

class Tranlsations
   Name

inputdatatable: column name : b.translations.name....  for a global filter search...

I could do that if I choose a conditional parameter with additionalSpecification.

Specifications.where(new DataTablesSpecification<T>(input))
							.and(additionalSpecification), getPageable(input));
To
Specifications.where(new DataTablesSpecification<T>(input))
							.or(additionalSpecification), getPageable(input));

**Comment by jitendra-xoriant** [comment]
Can you add custom where condition support?
for example if I want to get all employees where employer id =121
If API supports same, please guide me about how to do it.

Thanks

**Comment by darrachequesne** [comment]
Hi! @efriandika version 2.0 is out with QueryDSL support. I've updated the docs (with `QDataTablesRepository`) and will publish an example if I find some time.
