### ISSUE TITLE
Does it support mybatis3

### ISSUE THREAD

**Issue by wangjia2016** [darrachequesne/spring-data-jpa-datatables#41]
Since mybatis3 is more popular than Spring-data-jpa，
so how to conver this project to mybatis？
THKS。

**Comment by darrachequesne** [comment]
Hi! I'm not familiar with mybatis, is it possible to construct dynamic queries with it?

**Comment by wangjia2016** [comment]
@darrachequesne yes，it's very easy to construct dynamic queries. 
see http://www.mybatis.org/mybatis-3/index.html [http://www.mybatis.org/mybatis-3/index.html](url)

**Comment by darrachequesne** [comment]
Well, I'm afraid I won't have much time to spend on this, but I would be happy to merge any pull request adding that feature!

Also, as suggested [here](https://github.com/darrachequesne/spring-data-jpa-datatables/issues/25), that implementation should maybe have its own module (something like `mybatis-datatables`).
