### ISSUE TITLE
version 3.0 upload incomplete

### ISSUE THREAD

**Issue by goder037** [darrachequesne/spring-data-jpa-datatables#42]
I compare last version and 3.0, I find you forget to upload folder "paramter"  , Are you Sure?

**Comment by darrachequesne** [comment]
Hi! I moved every mapping class in the `mapping` directory, as that made more sense (at least to me) (hence the major bump)

So `org.springframework.data.jpa.datatables.parameter.ColumnParameter` is now 
`org.springframework.data.jpa.datatables.mapping.Column`.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
