### ISSUE TITLE
Dose search filter support regular search?

### ISSUE THREAD

**Issue by njwangchuan** [darrachequesne/spring-data-jpa-datatables#43]
The origin datatables support regular search in column.search() method, but it seems not working with Datatables<input> and will return an empty list with search. I noticed that the README file says filter with String Type will translate to "like'%<input>%'",does it means the lib is not support regex search yet?

Thanks

**Comment by darrachequesne** [comment]
Hi! Please see my response [here](https://github.com/darrachequesne/spring-data-jpa-datatables/issues/31#issuecomment-252354826).

tl;dr: the regex flag is not supported because JPA does not support regexp matching.

**Comment by njwangchuan** [comment]
@darrachequesne thank you very much.I just want to do exactly search and i find a solution with 'in' filters

**Comment by darrachequesne** [comment]
Great! Is there anything left? Else, could you please close the issue?
