### ISSUE TITLE
Cannot use different data for filter, sort and display ?

### ISSUE THREAD

**Issue by apri86** [darrachequesne/spring-data-jpa-datatables#47]
How can I use different data for the different data types requested by DataTables (ex: filter, sort and display)? I have refer to https://datatables.net/reference/option/columns.data, and use data as :
`"data": {
    "_": "phone",
    "filter": "phone_filter",
    "display": "phone_display"
}`

But, I got this error "java.lang.IllegalArgumentException: Property must not null or empty!".
Btw, thanks for this usefully library @darrachequesne ;)

**Comment by apri86** [comment]
Finally, I have use datatables render function, for data display property. Thanks

**Comment by darrachequesne** [comment]
I'm not too familiar with that format (I think it's called [orthogonal data](https://datatables.net/manual/data/orthogonal-data), isn't it?), but that case is indeed not handled currently.

Glad you found a solution! (that seems way easier than handling `filter`, `sort` args)
