### ISSUE TITLE
confilct 

### ISSUE THREAD

**Issue by wangfan0840** [darrachequesne/spring-data-jpa-datatables#48]
when i use it on embed tomact the javax.el-api was conflict with  tomcat-embed-el.

**Comment by darrachequesne** [comment]
You should be able to exclude the package:

```xml
<dependency>
  <groupId>com.github.darrachequesne</groupId>
  <artifactId>spring-data-jpa-datatables</artifactId>
  <version>3.1</version>
  <exclusions>
    <exclusion>
      <groupId>javax.el</groupId>
      <artifactId>javax.el-api</artifactId>
    </exclusion>
  </exclusions> 
</dependency>
```

**Comment by wangfan0840** [comment]
Thank you for your reply！
 I have tried this method before, when I run it withintellij idea  , everything is normal, but when I use Java -jar to deploy  on  the server, DataTables will not return data.

		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>
		</dependency>
		<dependency>
			<groupId>com.github.darrachequesne</groupId>
			<artifactId>spring-data-jpa-datatables</artifactId>
			<version>3.1</version>
			<exclusions>
				<exclusion>
					<groupId>javax.el</groupId>
					<artifactId>javax.el-api</artifactId>

				</exclusion>
			</exclusions>
		</dependency>

**Comment by darrachequesne** [comment]
Please reopen if needed.
