### ISSUE TITLE
Custom query

### ISSUE THREAD

**Issue by Dazzel** [darrachequesne/spring-data-jpa-datatables#53]
Is it possible to support the `@Query` annotation? Or even better, to allow custom repository methods with this?

I am trying to get something like this working:

```
DataTablesOutput<Entity> findAllBySearch(SearchEntity search, DataTablesInput input);
```

Or with `@Query`:
```
@Query("select e from entites where e.search = ?1")
DataTablesOutput<Entity> findAllBySearch(SearchEntity search, DataTablesInput input);
```

So `search` is an attribute of `entity` and I try to filter all entities by an search value.

I know, I can do this by Specifications or QueryDSL but does it work with normal spring repositories?

This behaviour would correlate with the default respoitories, like `Page<Entity> findAllBySearch(SearchEntity search, Pageable pageble)`

**Comment by darrachequesne** [comment]
I don't think it is possible, as there is a bit of dark magic happening with `Page<Entity> findAllBySearch(SearchEntity search, Pageable pageable)`.

Do you have a given use case where a Specification would not work?

**Comment by Dazzel** [comment]
I do not have any use case where specifications do not work. I was just
wondering if it would possible to get it working without it because it is
much more intuitive using the repository methods or the query annotations.

But I appreciate your fast anweser 😊

Damien Arrachequesne <notifications@github.com> schrieb am Mi., 15. März
2017, 22:22:
