### ISSUE TITLE
Searching with "+" throws SQLException

### ISSUE THREAD

**Issue by maheshrpm** [darrachequesne/spring-data-jpa-datatables#54]
Searching with column value only plus "**+**" throws SQLException.
Query formed as "**in ()**".

**Comment by darrachequesne** [comment]
Could you please provide a failing test case? Which version are you using? Which dbms?

**Comment by maheshrpm** [comment]
Column level searching with only "+" character from UI. Version: 4.0. DBMS: Postgresql: 9.2.5

`DataTablesInput(draw=2,
start=0,
length=10,
search=Search(value=,
regex=false),
order=[  
   Order(column=0,
   dir=asc)
],
columns=[  
   Column(data=username,
   name=,
   searchable=true,
   orderable=true,
   search=Search(value=+,
   regex=false)),
   Column(data=name,
   name=,
   searchable=true,
   orderable=true,
   search=Search(value=,
   regex=false)),
   Column(data=,
   name=,
   searchable=true,
   orderable=false,
   search=Search(value=,
   regex=false))
])`
