### ISSUE TITLE
DataTables warning: table id = student - java.lang.IllegalArgumentException: Unable to locate Attribute with the given name [] on this ManagedType [com.unsis.qualifications.model.Estudent]

### ISSUE THREAD

**Issue by angel-94** [darrachequesne/spring-data-jpa-datatables#61]
# ANGULARJS       
 estudiante.dtOptions = DTOptionsBuilder.newOptions()
            .withOption('ajax', {
                contentType: 'application/json',
                url: 'CALIFICACIONES/datatablepost',
                type: 'POST',
                data: function (d) {
                    return JSON.stringify(d);
                }
            })
            .withDataProp('data')
            .withOption('serverSide', true)
            .withPaginationType('full_numbers');
        estudiante.dtColumns = [
            DTColumnBuilder.newColumn('matricula').withTitle('Matrícula'),
            DTColumnBuilder.newColumn('persona.apellidoPaterno').withTitle('A. Paterno'),
            DTColumnBuilder.newColumn('persona.apellidoMaterno').withTitle('A. Materno'),
            DTColumnBuilder.newColumn('persona.nombre').withTitle('Nombre'),
            DTColumnBuilder.newColumn('semestre').withTitle('Semestre'),
            DTColumnBuilder.newColumn('grupo').withTitle('Grupo'),
            DTColumnBuilder.newColumn('promedioGeneral').withTitle('Promedio general').withClass('text-right'),
            DTColumnBuilder.newColumn('').withTitle('Acciones').notSortable().renderWith(actionsHtml)
        ];

# JAVA
	@JsonView(DataTablesOutput.View.class)
	@RequestMapping(path = "/datatablepost", method = RequestMethod.POST)
	public DataTablesOutput<Estudiante> getAllEStudiat(@Valid @RequestBody DataTablesInput input) {
		log.info("<<==================== DATATABLE ====================>>");
		log.info(input.toString());
		DataTablesOutput<Estudiante> ee = new DataTablesOutput<>();
		ee = dataTable.findAll(input);
		log.info(ee);
		return ee;
	}

**Comment by darrachequesne** [comment]
Hi! Could you please try with `DTColumnBuilder.newColumn('').withTitle('Acciones').notSortable().renderWith(actionsHtml).withOption('searchable', false)`?

Ref: https://github.com/l-lin/angular-datatables/issues/807

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
