### ISSUE TITLE
Server side filtering

### ISSUE THREAD

**Issue by JelleBlaauw** [darrachequesne/spring-data-jpa-datatables#62]
How to apply server side filtering? `findAll` obviously returns all columns, but there seems to be no way other than creating a whole new object to remove columns from the result. I tried messting around with the `DataTablesInput` object in my controller, but this didn't change the result.

Could you please help me out?

**Comment by darrachequesne** [comment]
You can add an additional `Specification` with:

```java
repository.findAll(input, specification);
```
Please see [here](https://github.com/darrachequesne/spring-data-jpa-datatables/blob/master/src/test/java/org/springframework/data/jpa/datatables/specification/TestSpecification.java) for an example.

**Comment by JelleBlaauw** [comment]
Thanks. It took some time to figure out how the Specification API works, but that's a non-datatables related issue.

This issue may be closed.
