### ISSUE TITLE
SQL command not properly ended in Spring with Oracle DB connection

### ISSUE THREAD

**Issue by thanushcst** [darrachequesne/spring-data-jpa-datatables#63]
Can i use spring-data-jpa-datatables to oracle DB? I got exception.
[Request processing failed; nested exception is org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Transaction marked as rollbackOnly] with root cause
javax.persistence.RollbackException: Transaction marked as rollbackOnly.

**Comment by darrachequesne** [comment]
Hi! I have not tested on oracle DB, and it seems Travis has no support for it ([ref](https://github.com/travis-ci/travis-ci/issues/3364)).

You should be able to retrieve the failing query by adding `org.hibernate.SQL` in `DEBUG` level.

**Comment by darrachequesne** [comment]
I'll close that for now, please reopen if needed.
