### ISSUE TITLE
How to implement where clause in Repository.

### ISSUE THREAD

**Issue by Ashwani-772** [darrachequesne/spring-data-jpa-datatables#72]
I am not able to implement where clause in it. It is working find in findAll() but i have to use where clause with Query. Please help me out on this.

**Comment by darrachequesne** [comment]
Please reopen if needed.

**Comment by AshrafPasha** [comment]
Your tutorial says "You can apply specific filter on a column with table.columns(<your column id>).search(<your filter>).draw(); (or table.columns(<your column name>:name)...) "

How do I apply specific filter using column name, which will result into a Where clause for that column name, I am struggling to do that, can you please elaborate? thanks a lot!
