### ISSUE TITLE
Salary range filter in advanced sample

### ISSUE THREAD

**Issue by krshkar** [darrachequesne/spring-data-jpa-datatables#74]
Your salary range filter in advanced sample doesn't work. You need to disable searchable option of column you try to filter.

**Comment by darrachequesne** [comment]
@krshkar it seems to work on my side. Do you get any error?

**Comment by krshkar** [comment]
I don't get any error but I always get empty table in response after filtering on salary. The bug is when you put value in search field of a column and haven't disabled searchable option, Min/Max Specification doesn't work and JPA looking for data that contains search value.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
