### ISSUE TITLE
Request resource from Oauth2 resource server

### ISSUE THREAD

**Issue by vanrin** [darrachequesne/spring-data-jpa-datatables#75]
How to request resource from Oauth2 resource server?
I have tried
` ajax: '/api/errorlog/all',`
 `serverSide: true,`
 ` processing: true,`
And give following error
`{error: "unauthorized", error_description: "Full authentication is required to access this resource"}
error
:
"unauthorized"
error_description
:
"Full authentication is required to access this resource"`

Note : I use spring boot with thymeleaf and try to request after authenticated.

**Comment by darrachequesne** [comment]
I think you should be able to achieve what you want with the [ajax](https://datatables.net/reference/option/ajax) option. Something like:
```js
var table = $('table#sample').DataTable({
  ajax: {
    beforeSend: (xhr) => xhr.setRequestHeader('Authorization', 'Bearer <token>')
  }
}
```

**Comment by vanrin** [comment]
thanks
