### ISSUE TITLE
Getting QueryParameterException: Position beyond number of declared ordinal parameters. Remember that ordinal parameters are 1-based! Position: 1; nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryParameterException: Position beyond number of declared ordinal parameters. Remember that ordinal parameters are 1-based! Position: 1

### ISSUE THREAD

**Issue by shrawani** [darrachequesne/spring-data-jpa-datatables#76]
Hi im trying to do a simple findall operation using spring-data-jpa-datatables. I'm getting this excpetion saying "Position beyond number of declared ordinal parameters". Can anyone help me on the same?

here my controller code : 
```java
@RequestMapping(value = { "/reports/patient" }, method = RequestMethod.POST, produces = {
	"application/json" }, consumes ={"application/json" })
	public DataTablesOutput<PatientDetailsDto> patientReport(@RequestBody DataTablesInput input) throws ApplicationException {
		DataTablesOutput<PatientDetailsDto> result = new DataTablesOutput<>();
		try{
		 DataTablesOutput<PatientDetail> paTablesOutput = patientRepository.findAll(input);
		 List<PatientDetailsDto> roomList = null;
		 processRoomList(roomList, paTablesOutput.getData());
		    result.setData(roomList);
		    result.setDraw(paTablesOutput.getDraw());
		    result.setError(paTablesOutput.getError());
		    result.setRecordsFiltered(paTablesOutput.getRecordsFiltered());
		    result.setRecordsTotal(paTablesOutput.getRecordsTotal());
		}
		catch (Exception e) {
			System.out.println(e.getMessage());
		}
		    return result;
	}
```

the input looks like this : 
DataTablesInput [draw=1, start=0, length=9, search=SearchParameter [value=, regex=false], order=[OrderParameter [column=0, dir=asc]], columns=[ColumnParameter [data=room_number, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=mrn, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=fname, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=mname, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=lname, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=status, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=checkin, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=checkout, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=extension, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=member1, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=memberExt1, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=member2, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=memberExt2, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=member3, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=memberExt3, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=member4, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=memberExt4, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=member5, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=memberExt5, name=, searchable=true, orderable=true, search=SearchParameter [value=, regex=false]], ColumnParameter [data=null, name=, searchable=true, orderable=false, search=SearchParameter [value=, regex=false]]]]

**Comment by darrachequesne** [comment]
The `data=null` of the last `ColumnParameter` looks weird, could you try with `searchable: false`?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
