### ISSUE TITLE
Retrieving data as JSON does not acccount for @JsonView annotation

### ISSUE THREAD

**Issue by iSosnitsky** [darrachequesne/spring-data-jpa-datatables#79]
Absence of @JsonView(DataTablesOutput.View.class) does not hide the property. - That's pretty much the issue. Putting it back and removing it again does not affect visibility of any property - i tried.

**Comment by iSosnitsky** [comment]
Okay, i narrowed it down a bit:
if we have a DataTable sending DataTableInput through POST-reqeust - DataTablesRepository outputs fields seemingly at random. But if it uses GET-request - JsonView annotation works all of the sudden.

**Comment by sebasira** [comment]
I'm having the same issue as you (earlier) do. I can not hide properties with @JsonView not even with @JsonIgnore. I'm using v4.3

**Comment by sebasira** [comment]
Well... it's strange.... now it's working with both GET and POST. I've switch back and forth from one method to another and they started to work (using @JsonView).

**Comment by iSosnitsky** [comment]
@sebasira In my case it doesn't work very consistently.

**Comment by sebasira** [comment]
@iSosnitsky give a few days and I'll put my code here

**Comment by iSosnitsky** [comment]
Now things get kinda odd.
It totally works if i use findAll(); with an empty DataTablesInput, like that:
```
@JsonView(DataTablesOutput.View.class)
    @RequestMapping(value = "/users", method = RequestMethod.GET)
    public DataTablesOutput<User> getUsers() {
        return userRepository.findAll(new DataTablesInput());
    }
```

But if i use DataTables provided input, it stops working:

```
@JsonView(DataTablesOutput.View.class)
    @RequestMapping(value = "/users", method = RequestMethod.GET)
    public DataTablesOutput<User> getUsers(@Valid DataTablesInput input) {
        return userRepository.findAll(input);
    }
```

Now i suspect DataTables itself.

i'm using DataTables 1.10.16

**Comment by darrachequesne** [comment]
Hi, I'm not able to reproduce with GET or POST requests: https://github.com/darrachequesne/spring-data-jpa-datatables-sample/tree/issue-79

In both cases, only `id`, `firstName` and `lastName` are displayed.

**Comment by iSosnitsky** [comment]
@darrachequesne Yeah, i reproduced it.
The issue was in WebConfig - i used Jackson-datatype-hibernate5 as a MessageConverter in my WebConfig.
Where can i show you modified  sample project?

**Comment by iSosnitsky** [comment]
@darrachequesne https://github.com/iSosnitsky/spring-data-jpa-datatables-sample

**Comment by darrachequesne** [comment]
@iSosnitsky thanks for providing a way to reproduce! It seems you have to manually disable the `DEFAULT_VIEW_INCLUSION` (it is disabled by default in Spring Boot, but was enabled in your case):

```diff
class HibernateAwareObjectMapper extends ObjectMapper {
    public HibernateAwareObjectMapper() {
        Hibernate5Module module = new Hibernate5Module();
        module.disable(Hibernate5Module.Feature.USE_TRANSIENT_ANNOTATION);
        this.enable(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT);
        this.enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY);
+       this.configure(MapperFeature.DEFAULT_VIEW_INCLUSION, false);
        this.registerModule(module);
    }
}
```

**Comment by iSosnitsky** [comment]
By the way, if you declare a lazy loaded field as a non-searchable, it won't be initialized:

```
{
                    data: 'office.city',
                    render: function (data) { return data ? data : '-'; },
                    searchable: false
                }
```

**Comment by darrachequesne** [comment]
@iSosnitsky let's add that to the README, if you will.

Regarding the lazy-loaded field, it seems you are right! Would you mind opening a new issue for that?

**Comment by iSosnitsky** [comment]
@darrachequesne Sure!

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
