### ISSUE TITLE
Searchable column with blank data properties cause error

### ISSUE THREAD

**Issue by DanneLeung** [darrachequesne/spring-data-jpa-datatables#85]
In some case, columns not set **"searchable=false"** and with **data=""** for custom rendering will cause [""(blank) property not found in xxx Class] error，I add column "data" property blank checking `StringUtils.hasText(column.getData())` in `AbstractPredicateBuilder.initTree` function to fix it temporally.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
