### ISSUE TITLE
How to change the result count using specification?

### ISSUE THREAD

**Issue by Mike-the-one** [darrachequesne/spring-data-jpa-datatables#89]
So my DB has items from multiple users.  The datatable is for individual users.  I need to use Specification to specify that the query is for a logged in user, which works fine.  Now the problem is the total entries.

For example, i have two users, user A has 57 items, user B has 600 items, and the datatable shows this:

```sh
Showing 1 to 10 of 57 entries (filtered from 657 total entries)
```

the total is for both user a and b.  But I only want to show this for user a, so I want this:

```sh
Showing 1 to 10 of 57 entries (filtered from 57 total entries).
```

How to do that?

thanks

**Comment by darrachequesne** [comment]
Hi! The `preFilteringSpecification` allows you to apply a specification on the total number of entities. Please see https://github.com/darrachequesne/spring-data-jpa-datatables#api

**Comment by Mike-the-one** [comment]
Thanks that worked!!!
