### ISSUE TITLE
it does work with datatable editor?

### ISSUE THREAD

**Issue by EduardoUcha** [darrachequesne/spring-data-jpa-datatables#9]
I was wondering if it works with datatable editor.

Thanks.

**Comment by darrachequesne** [comment]
Hi! There is currently no support of datatables editor INSERT/UPDATE/DELETE actions (as documented here https://editor.datatables.net/manual/server).

But any PR is welcome! :angel: (yet I'm not sure if it can truly be implemented in a generic way)
