### ISSUE TITLE
Date between not working, returns empty result

### ISSUE THREAD

**Issue by Mike-the-one** [darrachequesne/spring-data-jpa-datatables#92]
I am having problems to use date in between.  My order table has orderDateTime field, I would like to search the orders between two dates, but it just returns empty result.  

Here is the code

predicateDate = builder.between(root.<Date>get("orderDateTime"), d1, d2);

I return the predicateDate in the Specification class.

**Comment by darrachequesne** [comment]
Hi! Could you set the log level of `org.hibernate.SQL` to `DEBUG`, to see the generated query? What is the type of your field `orderDateTime`?

**Comment by darrachequesne** [comment]
I think this is the same issue as https://github.com/darrachequesne/spring-data-jpa-datatables/issues/94

Please see my comment: https://github.com/darrachequesne/spring-data-jpa-datatables/issues/94#issuecomment-441827285

**Comment by Mike-the-one** [comment]
Thanks @darrachequesne .

I already emptied the field.  Here is my code:

```sh
class SalesOrderAdditionalSpecification implements Specification<SalesOrder> {

        private static final long serialVersionUID = -5299972584411179584L;
        private DataTablesInput input;

        public SalesOrderAdditionalSpecification(DataTablesInput input) {
            this.input = input;
        }

        @Override
        public Predicate toPredicate(Root<SalesOrder> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
            // get the product name which is column 9
            Column col = input.getColumns().get(9);
            String val = col.getSearch().getValue();

            Predicate predicateProductName = null;
            Predicate predicate = null;
            if (val != null && !val.trim().isEmpty()) {
                Join<SalesOrder, OrderItem> orderItemsJoin = root.join("orderItems");
                Join<OrderItem, Product> productJoin = orderItemsJoin.join("product");

                predicateProductName = builder.like(productJoin.<String>get("productName"), "%" + val + "%");
                predicate = predicateProductName;
            }

            // get the product sku which is column 4
            col = input.getColumns().get(4);
            val = col.getSearch().getValue();
            Predicate predicateProductSku = null;

            if (val != null && !val.trim().isEmpty()) {
                Join<SalesOrder, OrderItem> orderItemsJoin = root.join("orderItems");
                Join<OrderItem, Product> productJoin = orderItemsJoin.join("product");

                predicateProductSku = builder.like(productJoin.<String>get("sku"), "%" + val + "%");
                if (predicate != null)
                    predicate = builder.and(predicate, predicateProductSku);
                else
                    predicate = predicateProductSku;
            }

            // date range
            col = input.getColumns().get(2);
            val = col.getSearch().getValue();
            col.getSearch().setValue("");
            Predicate predicateDate = null;

            if (val != null && !val.trim().isEmpty()) {
                SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
                int index = val.indexOf("-");
                
                String start = val.substring(0, index).trim();
                String end = val.substring(index + 1).trim();
                
                if (start.isEmpty() == false && end.isEmpty() == false) {
                    try {
                        Date d1 = formatter.parse(start);
                        Date d2 = formatter.parse(end);

                        predicateDate = builder.between(root.<Date>get("orderDateTime"), d1, d2);
                        

                    } catch (Exception e) {

                    }
                }

                if (predicate != null)
                    predicate = builder.and(predicate, predicateDate);
                else
                    predicate = predicateDate;
            }

            query.distinct(true);

            return predicate;

        }
    }
```

**Comment by Mike-the-one** [comment]
The field is ``DATE``.  I am trying the debug option now

**Comment by Mike-the-one** [comment]
this is the query:

``[DEBUG] 2018-11-27 03:07:57.377 [http-nio-0.0.0.0-8000-exec-7] SQL - select user0_.uacc_id as uacc_id1_22_, user0_.uacc_activation_token as uacc_act2_22_, user0_.uacc_activation_token_expire as uacc_act3_22_, user0_.uacc_active as uacc_act4_22_, user0_.uacc_avatar as uacc_ava5_22_, user0_.uacc_company as uacc_com6_22_, user0_.uacc_date_added as uacc_dat7_22_, user0_.uacc_date_fail_login_ban as uacc_dat8_22_, user0_.uacc_date_last_login as uacc_dat9_22_, user0_.uacc_email as uacc_em10_22_, user0_.uacc_fail_login_attempts as uacc_fa11_22_, user0_.uacc_fail_login_ip_address as uacc_fa12_22_, user0_.uacc_first_name as uacc_fi13_22_, user0_.uacc_forgotten_password_expire as uacc_fo14_22_, user0_.uacc_forgotten_password_token as uacc_fo15_22_, user0_.uacc_ip_address as uacc_ip16_22_, user0_.uacc_job_title as uacc_jo17_22_, user0_.uacc_last_name as uacc_la18_22_, user0_.uacc_password as uacc_pa19_22_, user0_.uacc_phone as uacc_ph20_22_, user0_.uacc_referral_code as uacc_re21_22_, user0_.uacc_referred_by as uacc_re22_22_, user0_.uacc_salt as uacc_sa23_22_, user0_.uacc_suspend as uacc_su24_22_, user0_.uacc_sync_inventory as uacc_sy25_22_, user0_.uacc_sync_message as uacc_sy26_22_, user0_.uacc_timezone_offset_mins as uacc_ti27_22_, user0_.uacc_update_email as uacc_up28_22_, user0_.uacc_update_email_token as uacc_up29_22_, user0_.uacc_website as uacc_we30_22_ from ems_user_accounts user0_ where user0_.uacc_email=?
[DEBUG] 2018-11-27 03:07:57.379 [http-nio-0.0.0.0-8000-exec-7] SQL - select usergroup0_.ugrp_user_fk as ugrp_use6_23_0_, usergroup0_.ugrp_id as ugrp_id1_23_0_, usergroup0_.ugrp_id as ugrp_id1_23_1_, usergroup0_.ugrp_admin as ugrp_adm2_23_1_, usergroup0_.ugrp_desc as ugrp_des3_23_1_, usergroup0_.ugrp_name as ugrp_nam4_23_1_, usergroup0_.ugrp_org_fk as ugrp_org5_23_1_, usergroup0_.ugrp_user_fk as ugrp_use6_23_1_, organizati1_.org_id as org_id1_6_2_, organizati1_.org_desc as org_desc2_6_2_, organizati1_.org_name as org_name3_6_2_ from ems_user_groups usergroup0_ inner join ems_org organizati1_ on usergroup0_.ugrp_org_fk=organizati1_.org_id where usergroup0_.ugrp_user_fk=?
[DEBUG] 2018-11-27 03:07:57.379 [http-nio-0.0.0.0-8000-exec-7] SQL - select payments0_.payment_uacc_fk as payment_6_19_0_, payments0_.payment_id as payment_1_19_0_, payments0_.payment_id as payment_1_19_1_, payments0_.payment_amount as payment_2_19_1_, payments0_.payment_date as payment_3_19_1_, payments0_.payment_gateway as payment_4_19_1_, payments0_.payment_txid as payment_5_19_1_, payments0_.payment_uacc_fk as payment_6_19_1_ from ems_subs_payments payments0_ where payments0_.payment_uacc_fk=?
[DEBUG] 2018-11-27 03:07:57.381 [http-nio-0.0.0.0-8000-exec-7] SQL - select count(salesorder0_.orders_id) as col_0_0_ from ems_sales_orders salesorder0_ where salesorder0_.orders_uacc_fk=?
[DEBUG] 2018-11-27 03:07:57.394 [http-nio-0.0.0.0-8000-exec-7] SQL - select distinct salesorder0_.orders_id as orders_i1_11_0_, channel2_.chann_id as chann_id1_10_1_, salesorder0_.orders_buyer_addr1 as orders_b2_11_0_, salesorder0_.orders_buyer_addr2 as orders_b3_11_0_, salesorder0_.orders_buyer_id as orders_b4_11_0_, salesorder0_.orders_chann_fk as orders_25_11_0_, salesorder0_.orders_buyer_city as orders_b5_11_0_, salesorder0_.orders_buyer_company as orders_b6_11_0_, salesorder0_.orders_buyer_country as orders_b7_11_0_, salesorder0_.orders_currency as orders_c8_11_0_, salesorder0_.orders_buyer_email as orders_b9_11_0_, salesorder0_.orders_ems_status as orders_10_11_0_, salesorder0_.orders_marked_shipped as orders_11_11_0_, salesorder0_.orders_buyer_name as orders_12_11_0_, salesorder0_.orders_order_datetime as orders_13_11_0_, salesorder0_.orders_orderid as orders_14_11_0_, salesorder0_.orders_buyer_phone as orders_15_11_0_, salesorder0_.orders_total_shipping_charges as orders_16_11_0_, salesorder0_.orders_shipping_method as orders_17_11_0_, salesorder0_.orders_buyer_state as orders_18_11_0_, salesorder0_.orders_status as orders_19_11_0_, salesorder0_.orders_tax_amount as orders_20_11_0_, salesorder0_.orders_total_amount as orders_21_11_0_, salesorder0_.orders_total_shipments as orders_22_11_0_, salesorder0_.orders_txid as orders_23_11_0_, salesorder0_.orders_uacc_fk as orders_26_11_0_, salesorder0_.orders_buyer_zip as orders_24_11_0_, channel2_.chann_active as chann_ac2_10_1_, channel2_.chann_autosync as chann_au3_10_1_, channel2_.chann_autosync_msg as chann_au4_10_1_, channel2_.chann_create_date as chann_cr5_10_1_, channel2_.chann_customer_update as chann_cu6_10_1_, channel2_.chann_data as chann_da7_10_1_, channel2_.chann_is_product_fetched as chann_is8_10_1_, channel2_.chann_logo_image as chann_lo9_10_1_, channel2_.chann_name as chann_n10_10_1_, channel2_.chann_packing_slip_message as chann_p11_10_1_, channel2_.chann_rate_provider as chann_r12_10_1_, channel2_.chann_saddr_fk as chann_s21_10_1_, channel2_.chann_store_update as chann_s13_10_1_, channel2_.chann_last_finish_sync_datetime as chann_l14_10_1_, channel2_.chann_sync_frequency_in_minutes as chann_s15_10_1_, channel2_.chann_last_start_sync_datetime as chann_l16_10_1_, channel2_.chann_sync_state as chann_s17_10_1_, channel2_.chann_token_expire_date as chann_t18_10_1_, channel2_.chann_type as chann_t19_10_1_, channel2_.chann_url as chann_u20_10_1_, channel2_.chann_uacc_fk as chann_u22_10_1_ from ems_sales_orders salesorder0_ left outer join ems_sales_channels channel1_ on salesorder0_.orders_chann_fk=channel1_.chann_id left outer join ems_sales_channels channel2_ on salesorder0_.orders_chann_fk=channel2_.chann_id where (lower(cast(salesorder0_.orders_order_datetime as char)) like ? escape ?) and salesorder0_.orders_uacc_fk=? order by salesorder0_.orders_orderid desc limit ?
``

**Comment by Mike-the-one** [comment]
Finally, I found the problem... yes it is the same issue as above, I cleared the search field but it is in the new class, the calling method still has the value there... that was the problem.

Thanks!
