### ISSUE TITLE
add summary properties

### ISSUE THREAD

**Issue by RicoSchueppel** [darrachequesne/spring-data-jpa-datatables#93]
hi .. is there a suggested way how to add 'summary properties' like the sum of values over a certain column (total value before pagination, but with applied filters) 

sum of this value in current page could be done in frontend, but i need the total of all pages (after filter applied)

thx in advance

**Comment by darrachequesne** [comment]
@RicoSchueppel hmm.. that's tricky. I guess you could reuse the [SpecificationBuilder](https://github.com/darrachequesne/spring-data-jpa-datatables/blob/master/src/main/java/org/springframework/data/jpa/datatables/SpecificationBuilder.java) class, and use it in another query (see [here](https://github.com/spring-projects/spring-data-jpa/blob/2.1.2.RELEASE/src/main/java/org/springframework/data/jpa/repository/support/SimpleJpaRepository.java#L620) for reference). That's all I can think of right now.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
