### ISSUE TITLE
Spring Boot DataTable TIMESTAMP range search

### ISSUE THREAD

**Issue by wallac3gg** [darrachequesne/spring-data-jpa-datatables#94]
Timestamp FIELD - "created" ( Postgresql )

In postgresql I have dates in format

createdDate : "2018-11-01 23:51:33.534" (TIMESTAMP WITHOUT TIME ZONE)

I would like to retrieve all orders for 2018-11-01.

Spring DATA JPA - DATATABLE METHOD

```java
@Override
public Predicate toPredicate(Root<Parlamentares> root, CriteriaQuery<?> query, CriteriaBuilder criteriaBuilder) {

  Expression<Timestamp> createdDate = root.get("created").as(Timestamp.class);

  if (dateBegi != null && dateEnd != null) {
    return criteriaBuilder.between(createdDate, dateBegi, dateEnd);
  } else if (dateBegi != null) {
    return criteriaBuilder.greaterThanOrEqualTo(createdDate, dateBegi);
  } else if (dateEnd != null) {
    return criteriaBuilder.lessThanOrEqualTo(createdDate, dateEnd);
  } else {
    return criteriaBuilder.conjunction();
  }
}
```
Everything works fine when i'm using "createdDate DATE column".

dateBegi : "2018-11-01" comes from daterangepick.

How to resolve this problem? Any ideia ?

Edit: code block

**Comment by darrachequesne** [comment]
What are the Java types of the  `dateBegi` and `dateEnd` variables? `java.sql.Date` ? `java.util.Timestamp`? 

Are you able to reproduce the issue, by forking the test [here](https://github.com/darrachequesne/spring-data-jpa-datatables/blob/master/src/test/java/org/springframework/data/jpa/datatables/model/Employee.java) for example?

You could also enable set the log level of `org.hibernate.SQL` to `DEBUG`, to see the generated query.

**Comment by wallac3gg** [comment]
Both comes as STRING from (DataTablesInput input), then i convert to java.util.Date.

dateBegi and dateEnd both variables java.util.Date. I tried putting both variables java.sql.Date and it not worked. 

Tried Expression with java.util.Date, without success.

SQL DEBUG :  

==================
2018-11-26 : DEBUG 3340 --- [nio-8080-exec-6] org.hibernate.SQL   : select parlamenta0_.id as id1_5_, parlamenta0_.age as age2_5_, parlamenta0_.created as created3_5_, parlamenta0_.nascimento as nascimen4_5_, parlamenta0_.nome as nome5_5_, parlamenta0_.salary as salary6_5_ from parlamentares parlamenta0_ where (lower(cast(parlamenta0_.created as varchar(255))) like ? escape ?) and cast(parlamenta0_.created as timestamp)>=? limit ?

========================

**Comment by darrachequesne** [comment]
I think you have to reset the value of the `createdAt`  in the `DataTablesInput` object, so that the default filter (in your debug log `lower(cast(parlamenta0_.created as varchar(255))) like ? escape ?`) is not added to the query:

```java
ColumnParameter parameter0 = input.getColumns().get(0);
Specification additionalSpecification = getAdditionalSpecification(parameter0.getSearch().getValue());
parameter0.getSearch().setValue(""); // <-- this line
return userRepository.findAll(input, additionalSpecification);
```

**Comment by wallac3gg** [comment]
Finally, that's the point, you are correct :  

Solution for POSTGRESQL TIMESTAMP DATE RANGE, just reset the value : 

public DataTablesOutput<Parlamentares> listParl(@Valid DataTablesInput input) {
		
		Column parameter0 = input.getColumns().get(6);
		Specification<Parlamentares> additionalSpecification  = new DateSpecification(parameter0.getSearch().getValue());
		parameter0.getSearch().setValue(""); 
		return repository.findAll(input, additionalSpecification );
	}




But why i have to reset the value with a database TIMESTAMP column ? database DATE column works fine without reset. Anyway thank you my friend.

**Comment by darrachequesne** [comment]
You're welcome. :+1:

**Comment by Mike-the-one** [comment]
I already emptied the search.  Here is my code:

```sh
class SalesOrderAdditionalSpecification implements Specification<SalesOrder> {

        private static final long serialVersionUID = -5299972584411179584L;
        private DataTablesInput input;

        public SalesOrderAdditionalSpecification(DataTablesInput input) {
            this.input = input;
        }

        @Override
        public Predicate toPredicate(Root<SalesOrder> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
            // get the product name which is column 9
            Column col = input.getColumns().get(9);
            String val = col.getSearch().getValue();

            Predicate predicateProductName = null;
            Predicate predicate = null;
            if (val != null && !val.trim().isEmpty()) {
                Join<SalesOrder, OrderItem> orderItemsJoin = root.join("orderItems");
                Join<OrderItem, Product> productJoin = orderItemsJoin.join("product");

                predicateProductName = builder.like(productJoin.<String>get("productName"), "%" + val + "%");
                predicate = predicateProductName;
            }

            // get the product sku which is column 4
            col = input.getColumns().get(4);
            val = col.getSearch().getValue();
            Predicate predicateProductSku = null;

            if (val != null && !val.trim().isEmpty()) {
                Join<SalesOrder, OrderItem> orderItemsJoin = root.join("orderItems");
                Join<OrderItem, Product> productJoin = orderItemsJoin.join("product");

                predicateProductSku = builder.like(productJoin.<String>get("sku"), "%" + val + "%");
                if (predicate != null)
                    predicate = builder.and(predicate, predicateProductSku);
                else
                    predicate = predicateProductSku;
            }

            // date range
            col = input.getColumns().get(2);
            val = col.getSearch().getValue();
            col.getSearch().setValue("");
            Predicate predicateDate = null;

            if (val != null && !val.trim().isEmpty()) {
                SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
                int index = val.indexOf("-");
                
                String start = val.substring(0, index).trim();
                String end = val.substring(index + 1).trim();
                
                if (start.isEmpty() == false && end.isEmpty() == false) {
                    try {
                        Date d1 = formatter.parse(start);
                        Date d2 = formatter.parse(end);

                        predicateDate = builder.between(root.<Date>get("orderDateTime"), d1, d2);
                        

                    } catch (Exception e) {

                    }
                }

                if (predicate != null)
                    predicate = builder.and(predicate, predicateDate);
                else
                    predicate = predicateDate;
            }

            query.distinct(true);

            return predicate;

        }
    }
```
