### ISSUE TITLE
Columns.search () is throwing expecting HQL parser issue - CLOSE, found '(' [org.hibernate.hql.ast.HqlParser]  processEqualityExpression() : No expression to process! 

### ISSUE THREAD

**Issue by AshrafPasha** [darrachequesne/spring-data-jpa-datatables#95]
var table = $('table#Ashraf').DataTable({
							'ajax' : '/financialRecon/financialRecon/fedGLResultsGET',
							'serverSide' : true,
							dom : 'lBfrtip',
							deferRender:true,
							buttons : ['excel','csv','pdf','copy'],
							columns : [
										{data : 'sedId'},
										{data : 'cnsmrPymntBtchId'},
										{data : 'balanceDate'},
										{data : 'transCategory'},
										{data : 'cnsmrPymntCmmntTxt'},
										{data : 'sspnsCnsmrTrnsctnId'}
									  ]
						});
			    table.columns( 1 ).search( '962' );
			    table.draw();

on the server side it throws a HQL Parser issue, 
--------CLOSE, found '(' [org.hibernate.hql.ast.HqlParser]  processEqualityExpression() : No expression to process! 

Also kindly can you show me how to search by column name and value, I am struggling a lot it to figure it out, datatables.net does not give my info.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
