### ISSUE TITLE
Working well on localhost only

### ISSUE THREAD

**Issue by motawfik98** [darrachequesne/spring-data-jpa-datatables#99]
When I run the program on the localhost, the framework is working properly and retrieving the data as required, while uploading it returns an empty array containing no data with HTTP response 200
This is the response
{"draw":1,"recordsTotal":0,"recordsFiltered":0,"data":[],"error":"org.hibernate.TransactionException: JDBC begin transaction failed: "} 
The database is on the same machine (localhost) and I am able to connect to it as I have a login page and when I add a new row it is added to the database but I still can't view it.

**Comment by JonasGroeger** [comment]
Could you show the full error message? Otherwise I'm unable to help.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
